#权限节点
#


settings:
  interval: 60 #赠送飞行时间的在线时长间隔(秒)
  giveTime: 6 #每满足一次赠送条件时 赠送的飞行时长(秒)
  alert: #玩家通知
    enable: true #是否启用玩家通知
    # 通知消息
    #  - 支持使用 “&” 代替小结号作为颜色符号
    #  - 变量： %(interval) 间隔时间
    #  - 变量： %(time)     赠送时间
    message: "&7您刚刚完成了一次在线 &f%(interval) 秒&7，获增了 &f%(time) 秒&7飞行时间。"