name: TimeForFlight
main: com.carmwork.plugin.timeforflight.Main
version: 1.0.0 - SNAPSHOT
author: CarmJos
depend: [ProtocolLib]
commands:
  TimeForFlight:
    permission: timeforflight.admin
    description: 管理员指令
    permission-message: "§c抱歉！§7但您没有这么做的权限。"
    aliases:
      - flighttime
  ToggleFly:
    aliases:
      - ToggleFlight
permissions:
  timeforflight.unlimited:
    default: op
    description: "无限制飞行，不计算飞行时间"
  timeforflight.allowflight:
    description: "拥有此权限的玩家允许飞行"
  timeforflight.getflighttime:
    description: "拥有次权限的玩家会获赠飞行时间"